CREATE TABLE TB_SISWA (
	ID_SISWA INT IDENTITY(1,1) PRIMARY KEY,
	NIS VARCHAR(10) NULL,
	NAMA VARCHAR(50) NULL,
	ALAMAT VARCHAR(100) NULL,
	TG_LAHIR DATE NULL,
	J_KELAMIN VARCHAR(1) NULL
);

ALTER TABLE TB_SISWA ALTER COLUMN J_KELAMIN VARCHAR(10);

SELECT TS.NIS, TS.NAMA FROM TB_SISWA ts;

INSERT INTO TB_SISWA (NIS, NAMA, ALAMAT, TG_LAHIR, J_KELAMIN)
VALUES('1001','RAFIF','BOGOR','1999-08-29','PRIA');

INSERT INTO TB_SISWA (NIS, NAMA, ALAMAT, TG_LAHIR, J_KELAMIN)
VALUES('1002','ANIS','MALANG','2010-10-06','WANITA');

SELECT * FROM TB_SISWA ts;

SELECT TS.NIS, TS.NAMA, TS.TG_LAHIR FROM TB_SISWA ts WHERE ALAMAT = 'BOGOR';

SELECT * FROM TB_SISWA WHERE ALAMAT LIKE 'MA%';

SELECT * FROM TB_SISWA WHERE TG_LAHIR BETWEEN '2010-10-05' AND '2010-10-10';

UPDATE TB_SISWA SET NAMA = 'CHARLES WHITE' WHERE NIS = '1002';

UPDATE TB_SISWA SET J_KELAMIN  = 'PRIA' WHERE NAMA = 'CHARLES WHITE';

INSERT INTO TB_SISWA (NIS, NAMA, ALAMAT, TG_LAHIR, J_KELAMIN)
VALUES('1003','MATT BLACK','JAKARTA','2012-12-10','PRIA');

DELETE TB_SISWA WHERE NIS = '1003';
