--A--
CREATE DATABASE STAFF;

USE STAFF;

--B--
CREATE TABLE DATA_STAFF (
	NIK INT IDENTITY(1,1) PRIMARY KEY,
	NAMA VARCHAR(50) NULL,
	ALAMAT VARCHAR(200) NULL,
	HANDPHONE VARCHAR(15)
);

--C--
INSERT INTO DATA_STAFF (NAMA, ALAMAT, HANDPHONE)
VALUES('RAFIF','INDONESIA','0812');

INSERT INTO DATA_STAFF (NAMA, ALAMAT, HANDPHONE)
VALUES('JOHN','ALBANIA','0813');

INSERT INTO DATA_STAFF (NAMA, ALAMAT, HANDPHONE)
VALUES('PIERRE','FRANCE','0814');

INSERT INTO DATA_STAFF (NAMA, ALAMAT, HANDPHONE)
VALUES('HENRY','CZECH REPUBLIC','0815');

INSERT INTO DATA_STAFF (NAMA, ALAMAT, HANDPHONE)
VALUES('ARTHUR','UNITED STATES','0816');

INSERT INTO DATA_STAFF (NAMA, ALAMAT, HANDPHONE)
VALUES('JANE','UNITED KINGDOM','0817');

--D--
ALTER TABLE DATA_STAFF ADD JOINDATE DATE NULL;

--E--
UPDATE DATA_STAFF SET JOINDATE = '2012-12-10' WHERE NIK = '1';
UPDATE DATA_STAFF SET JOINDATE = '2012-12-11' WHERE NIK = '2';
UPDATE DATA_STAFF SET JOINDATE = '2012-12-12' WHERE NIK = '3';
UPDATE DATA_STAFF SET JOINDATE = '2012-12-13' WHERE NIK = '4';
UPDATE DATA_STAFF SET JOINDATE = '2012-12-14' WHERE NIK = '5';
UPDATE DATA_STAFF SET JOINDATE = '2012-12-15' WHERE NIK = '6';

--F--
SELECT TOP 2 * FROM DATA_STAFF ds;

--G--
SELECT TOP 3 * FROM DATA_STAFF ds;

--H--
CREATE TABLE STAFF_OUTSOURCE (
	NIK INT IDENTITY(1,1) PRIMARY KEY,
	NAMA VARCHAR(50) NULL,
	ALAMAT VARCHAR(200) NULL,
	HANDPHONE VARCHAR(15),
	JOINDATE DATE NULL
);

--I--
INSERT INTO STAFF_OUTSOURCE (NAMA, ALAMAT, HANDPHONE, JOINDATE)
VALUES('Anthony','INDONESIA','0812', '2012-12-10');

INSERT INTO STAFF_OUTSOURCE (NAMA, ALAMAT, HANDPHONE, JOINDATE)
VALUES('Jana','ALBANIA','0813', '2012-12-11');

INSERT INTO STAFF_OUTSOURCE (NAMA, ALAMAT, HANDPHONE, JOINDATE)
VALUES('Brianna','FRANCE','0814', '2012-12-12');

INSERT INTO STAFF_OUTSOURCE (NAMA, ALAMAT, HANDPHONE, JOINDATE)
VALUES('Jethro','CZECH REPUBLIC','0815', '2012-12-13');

INSERT INTO STAFF_OUTSOURCE (NAMA, ALAMAT, HANDPHONE, JOINDATE)
VALUES('Merlin','UNITED STATES','0816', '2012-12-14');

INSERT INTO STAFF_OUTSOURCE (NAMA, ALAMAT, HANDPHONE, JOINDATE)
VALUES('Aizah','UNITED KINGDOM','0817', '2012-12-15');

INSERT INTO STAFF_OUTSOURCE (NAMA, ALAMAT, HANDPHONE, JOINDATE)
VALUES('Marc','UNITED KINGDOM','0817', '2012-12-16');

INSERT INTO STAFF_OUTSOURCE (NAMA, ALAMAT, HANDPHONE, JOINDATE)
VALUES('Muhammad','UNITED KINGDOM','0817', '2012-12-17');

INSERT INTO STAFF_OUTSOURCE (NAMA, ALAMAT, HANDPHONE, JOINDATE)
VALUES('Corinne','UNITED KINGDOM','0817', '2012-12-18');

INSERT INTO STAFF_OUTSOURCE (NAMA, ALAMAT, HANDPHONE, JOINDATE)
VALUES('Sullivan','UNITED KINGDOM','0817', '2012-12-19');

--J--
SELECT DATA_STAFF.*, STAFF_OUTSOURCE.* FROM DATA_STAFF INNER JOIN STAFF_OUTSOURCE
ON DATA_STAFF.JOINDATE = STAFF_OUTSOURCE.JOINDATE;

--K--
SELECT STAFF_OUTSOURCE.* FROM STAFF_OUTSOURCE RIGHT JOIN DATA_STAFF
ON DATA_STAFF.JOINDATE = STAFF_OUTSOURCE.JOINDATE;

--L--
SELECT DATA_STAFF.* FROM DATA_STAFF LEFT JOIN STAFF_OUTSOURCE
ON DATA_STAFF.JOINDATE = STAFF_OUTSOURCE.JOINDATE;

--M--
SELECT * FROM DATA_STAFF FULL JOIN STAFF_OUTSOURCE
ON DATA_STAFF.JOINDATE = STAFF_OUTSOURCE.JOINDATE;
